//获取用户信息
export const FETCH_GET_USERINFO_LOADING = "FETCH_GET_USERINFO_LOADING";
export const FETCH_GET_USERINFO_SUCCESS = "FETCH_GET_USERINFO_SUCCESS";
export const FETCH_GET_USERINFO_ERROR = "FETCH_GET_USERINFO_ERROR";