//获取用户信息
export const FETCH_GET_USERINFO_LOADING = "FETCH_GET_USERINFO_LOADING";
export const FETCH_GET_USERINFO_SUCCESS = "FETCH_GET_USERINFO_SUCCESS";
export const FETCH_GET_USERINFO_ERROR = "FETCH_GET_USERINFO_ERROR";

// 登陆
export const FETCH_LOGIN_LOADING = "FETCH_LOGIN_LOADING";
export const FETCH_LOGIN_ERROR = "FETCH_LOGIN_ERROR";
export const FETCH_LOGIN_SUCCESS = "FETCH_LOGIN_SUCCESS";
